### ISSUE TITLE
Support for WordPress 4.2 `is-dismissible` class

### ISSUE THREAD

**Issue by grappler** [CalderaWP/dismissible_notice#5]
In [WordPress 4.2](https://make.wordpress.org/core/2015/04/23/spinners-and-dismissible-admin-notices-in-4-2/) a new class was introduced to add a dismiss button.

I made some changes to switch to using the class `is-dismissible` https://github.com/grappler/dismissible_notice/commit/7ca7b9d50dcd306944abadd471749754c0627a9b

I am not sure how you want to support it in this class.

**Comment by Shelob9** [comment]
That commit has two things in it:

1) Allowing for skipping the prefixing of the ignore key/ and the `sub_str()`, which was designed to limit length from getting too long.
- I wanted to use a prefix so I could clear all of them with a LIKE comparison on the `meta_key` column. But I guess this is good.

2) Adding the `is-dismissible` class.
- Makes sense, but my concern is pre-4.2 compatibility, and backwords compat in CWP plugins. What if it was just changed to add both classes?

**Comment by grappler** [comment]
Yes, the commit has multiple things in it. I wanted to commit all of my changes in one branch. We can discuss 1. further in https://github.com/CalderaWP/dismissible_notice/pull/4
1. The best way to provide backwards compatibility would be to add the JS that WordPress uses in 4.2

The two changesets.
https://core.trac.wordpress.org/changeset/32068
https://core.trac.wordpress.org/changeset/31973

This is the JS needed

``` js
    // Make notices dismissible
    $( '.notice.is-dismissible' ).each( function() {
        var $this = $( this ),
            $button = $( '<button type="button" class="notice-dismiss"><span class="screen-reader-text"></span></button>' ),
            btnText = caldera_commonL10n.dismiss || '';

        // Ensure plain text
        $button.find( '.screen-reader-text' ).text( btnText );

        $this.append( $button );

        $button.on( 'click.wp-dismiss-notice', function( event ) {
            event.preventDefault();
            $this.fadeTo( 100 , 0, function() {
                $(this).slideUp( 100, function() {
                    $(this).remove();
                });
            });
        });
    });
```

This PHP then internationalizes the elements

``` php
    wp_localize_script( 'caldera-common', 'caldera_commonL10n', array(
        'dismiss'    => __( 'Dismiss this notice.', 'plugin-domain' ),
    ) );
```

I am not sure what CSS changes need to be made.

**Comment by Shelob9** [comment]
As long as it works in pre 4.2 I'm OK with that change.

**Comment by grappler** [comment]
How many WP versions do you want to support? In the current code dashicons are being used which were only added in 3.8. I have been able to test the code for it to work in 3.7.8 but there are no dashicons before 3.8.

Is support till WP 3.8 enough?
